--- #YAML:1.0
name:               WAP-wbxml
version:            1.12
abstract:           Binarization of XML file used by Wireless Application Protocol
author:
    - Francois PERRAD (francois.perrad@gadz.org)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dumper:   0
    I18N::Charset:  1.15
    XML::DOM:       1.25
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
