--- #YAML:1.0
name:                WAP-wbxml
version:             1.11
abstract:            Binarization of XML file used by Wireless Application Protocol
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.3201
distribution_type:   module
requires:     
    Data::Dumper:                  0
    I18N::Charset:                 1.15
    XML::DOM:                      1.25
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Francois PERRAD (francois.perrad@gadz.org)
