# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WAP-wbxml
version:      1.10
version_from: wbxml.pm
installdirs:  site
requires:
    Data::Dumper:                  0
    I18N::Charset:                 1.15
    XML::DOM:                      1.25

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
