
test:
	xmlc sample_10.wml
	xmlc sample_11.wml
	xmlc sample_12.wml
	xmlc sample_13.wml
	xmlc sample_10.si
	xmlc sample_10.sl
	xmlc sample_10.co
	xmlc sample_11.channel
	xmlc sample_12.channel
	xmlc sample_12.wta-wml
	xmlc basic_10.html
	xmlc strict_10.html
	xmlc personal.xml

out:
	xmld sample_10.wmlc		sample_wml10.out
	xmld sample_11.wmlc		sample_wml11.out
	xmld sample_12.wmlc		sample_wml12.out
	xmld sample_13.wmlc		sample_wml13.out
	xmld sample_10.sic		sample_si10.out
	xmld sample_10.slc		sample_sl10.out
	xmld sample_10.coc		sample_co10.out
	xmld sample_11.channelc		sample_channel11.out
	xmld sample_12.channelc		sample_channel12.out
	xmld sample_12.wta-wmlc		sample_wta-wml12.out
	xmld basic_10.htmlc		basic_10.out
	xmld strict_10.htmlc		strict_10.out
	xmld personal.xmlc		personal.out

