
test:
	wbxmlc.pl sample_10.wml
	wbxmlc.pl sample_11.wml
	wbxmlc.pl sample_12.wml
	wbxmlc.pl sample_13.wml
	wbxmlc.pl sample_10.si
	wbxmlc.pl sample_10.sl
	wbxmlc.pl sample_10.co
	wbxmlc.pl sample_11.channel
	wbxmlc.pl sample_12.channel
	wbxmlc.pl sample_12.wta-wml
	wbxmlc.pl basic_10.html
	wbxmlc.pl strict_10.html
	wbxmlc.pl personal.xml

out:
	wbxmld.pl sample_10.wmlc	sample_wml10.out
	wbxmld.pl sample_11.wmlc	sample_wml11.out
	wbxmld.pl sample_12.wmlc	sample_wml12.out
	wbxmld.pl sample_13.wmlc	sample_wml13.out
	wbxmld.pl sample_10.sic		sample_si10.out
	wbxmld.pl sample_10.slc		sample_sl10.out
	wbxmld.pl sample_10.coc		sample_co10.out
	wbxmld.pl sample_11.channelc	sample_channel11.out
	wbxmld.pl sample_12.channelc	sample_channel12.out
	wbxmld.pl sample_12.wta-wmlc	sample_wta-wml12.out
	wbxmld.pl basic_10.htmlc	basic_10.out
	wbxmld.pl strict_10.htmlc	strict_10.out
	wbxmld.pl personal.xmlc		personal.out

